### ISSUE TITLE
Paket.toml - Add `dependencies` field

### ISSUE THREAD

**Issue by eminfedar** [pardus-topluluk/paket#2]
**Acceptance Criteria:**
* [ ] Dependencies struct implemented and added in Config
* [ ] Basic tests are working. (tests/toml_parse.rs)
* [ ] Full tests are working. (tests/toml_parse.rs)
* [ ] Documentations on every struct, property and function is written with `///` three slashes.

**Implementation Details:**
Config Struct:
```rust
#[derive(Deserialize, Serialize)]
struct Config {
    package: Package,
    dependencies: Option<Dependencies>,
}
```

Dependencies Struct:
```rust
#[derive(Deserialize, Serialize)]
struct Dependencies {
    application: Option<Vec<String>>,
    library: Option<Vec<String>>,
    development: Option<Vec<String>>,
}
```
**These fields may be updated, names may change or new fields may be added.**

Example **Paket.toml**:
```toml
[package]
name = "paket-ornek"
version = "0.1.0"
maintainers = ["Emin Fedar <eminfedar@gmail.com>"]

description = "A paket package example."
license = "MIT"

architectures = ["amd64"]

[dependencies]
application = ["python3.11", "python3-gi"]
library = ["libgtk-3-0", "libglib2.0.0", "libpango-1.0-0"]
# development = ["libgtk-3-0-dev"] # This field is only needed if the paket type is Source Code
```
